version: '3.8'

services:
  app:
    container_name: py_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  mongo:
    image: mongo:7.0.3
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpwd
    ports:
      - "27017:27017"
    volumes:
      - "./docker/mongo/data:/data/db"
      - "./docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge